// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infovis.proto3

package Infovis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Geometry struct {
	Fram                 int32     `protobuf:"varint,1,opt,name=fram,proto3" json:"fram,omitempty"`
	Iden                 int64     `protobuf:"varint,2,opt,name=iden,proto3" json:"iden,omitempty"`
	Type                 int32     `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Mask                 int32     `protobuf:"varint,4,opt,name=mask,proto3" json:"mask,omitempty"`
	Cnts                 []int32   `protobuf:"varint,5,rep,packed,name=cnts,proto3" json:"cnts,omitempty"`
	Posx                 []float64 `protobuf:"fixed64,6,rep,packed,name=posx,proto3" json:"posx,omitempty"`
	Posy                 []float64 `protobuf:"fixed64,7,rep,packed,name=posy,proto3" json:"posy,omitempty"`
	Posz                 []float64 `protobuf:"fixed64,8,rep,packed,name=posz,proto3" json:"posz,omitempty"`
	Size                 float64   `protobuf:"fixed64,9,opt,name=size,proto3" json:"size,omitempty"`
	Colr                 uint32    `protobuf:"fixed32,10,opt,name=colr,proto3" json:"colr,omitempty"`
	Text                 string    `protobuf:"bytes,11,opt,name=text,proto3" json:"text,omitempty"`
	Glyp                 int32     `protobuf:"varint,12,opt,name=glyp,proto3" json:"glyp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_24c2a9f4cd96d406, []int{0}
}

func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (m *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(m, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

func (m *Geometry) GetFram() int32 {
	if m != nil {
		return m.Fram
	}
	return 0
}

func (m *Geometry) GetIden() int64 {
	if m != nil {
		return m.Iden
	}
	return 0
}

func (m *Geometry) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Geometry) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *Geometry) GetCnts() []int32 {
	if m != nil {
		return m.Cnts
	}
	return nil
}

func (m *Geometry) GetPosx() []float64 {
	if m != nil {
		return m.Posx
	}
	return nil
}

func (m *Geometry) GetPosy() []float64 {
	if m != nil {
		return m.Posy
	}
	return nil
}

func (m *Geometry) GetPosz() []float64 {
	if m != nil {
		return m.Posz
	}
	return nil
}

func (m *Geometry) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Geometry) GetColr() uint32 {
	if m != nil {
		return m.Colr
	}
	return 0
}

func (m *Geometry) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Geometry) GetGlyp() int32 {
	if m != nil {
		return m.Glyp
	}
	return 0
}

type Location struct {
	Posx                 float64  `protobuf:"fixed64,1,opt,name=posx,proto3" json:"posx,omitempty"`
	Posy                 float64  `protobuf:"fixed64,2,opt,name=posy,proto3" json:"posy,omitempty"`
	Posz                 float64  `protobuf:"fixed64,3,opt,name=posz,proto3" json:"posz,omitempty"`
	Rotw                 float64  `protobuf:"fixed64,4,opt,name=rotw,proto3" json:"rotw,omitempty"`
	Rotx                 float64  `protobuf:"fixed64,5,opt,name=rotx,proto3" json:"rotx,omitempty"`
	Roty                 float64  `protobuf:"fixed64,6,opt,name=roty,proto3" json:"roty,omitempty"`
	Rotz                 float64  `protobuf:"fixed64,7,opt,name=rotz,proto3" json:"rotz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_24c2a9f4cd96d406, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetPosx() float64 {
	if m != nil {
		return m.Posx
	}
	return 0
}

func (m *Location) GetPosy() float64 {
	if m != nil {
		return m.Posy
	}
	return 0
}

func (m *Location) GetPosz() float64 {
	if m != nil {
		return m.Posz
	}
	return 0
}

func (m *Location) GetRotw() float64 {
	if m != nil {
		return m.Rotw
	}
	return 0
}

func (m *Location) GetRotx() float64 {
	if m != nil {
		return m.Rotx
	}
	return 0
}

func (m *Location) GetRoty() float64 {
	if m != nil {
		return m.Roty
	}
	return 0
}

func (m *Location) GetRotz() float64 {
	if m != nil {
		return m.Rotz
	}
	return 0
}

type Request struct {
	Show                 int32       `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reset_               bool        `protobuf:"varint,3,opt,name=reset,proto3" json:"reset,omitempty"`
	Upsert               []*Geometry `protobuf:"bytes,4,rep,name=upsert,proto3" json:"upsert,omitempty"`
	Delete               []int64     `protobuf:"varint,5,rep,packed,name=delete,proto3" json:"delete,omitempty"`
	Viewloc              *Location   `protobuf:"bytes,6,opt,name=viewloc,proto3" json:"viewloc,omitempty"`
	Toolloc              *Location   `protobuf:"bytes,7,opt,name=toolloc,proto3" json:"toolloc,omitempty"`
	Offsetloc            *Location   `protobuf:"bytes,8,opt,name=offsetloc,proto3" json:"offsetloc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_24c2a9f4cd96d406, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetShow() int32 {
	if m != nil {
		return m.Show
	}
	return 0
}

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Request) GetReset_() bool {
	if m != nil {
		return m.Reset_
	}
	return false
}

func (m *Request) GetUpsert() []*Geometry {
	if m != nil {
		return m.Upsert
	}
	return nil
}

func (m *Request) GetDelete() []int64 {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Request) GetViewloc() *Location {
	if m != nil {
		return m.Viewloc
	}
	return nil
}

func (m *Request) GetToolloc() *Location {
	if m != nil {
		return m.Toolloc
	}
	return nil
}

func (m *Request) GetOffsetloc() *Location {
	if m != nil {
		return m.Offsetloc
	}
	return nil
}

type Response struct {
	Shown                int32     `protobuf:"varint,1,opt,name=shown,proto3" json:"shown,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Hover                []int64   `protobuf:"varint,3,rep,packed,name=hover,proto3" json:"hover,omitempty"`
	Unhover              []int64   `protobuf:"varint,4,rep,packed,name=unhover,proto3" json:"unhover,omitempty"`
	Select               []int64   `protobuf:"varint,5,rep,packed,name=select,proto3" json:"select,omitempty"`
	Deselect             []int64   `protobuf:"varint,6,rep,packed,name=deselect,proto3" json:"deselect,omitempty"`
	Viewloc              *Location `protobuf:"bytes,7,opt,name=viewloc,proto3" json:"viewloc,omitempty"`
	Toolloc              *Location `protobuf:"bytes,8,opt,name=toolloc,proto3" json:"toolloc,omitempty"`
	Offsetloc            *Location `protobuf:"bytes,9,opt,name=offsetloc,proto3" json:"offsetloc,omitempty"`
	Depressed            uint32    `protobuf:"fixed32,10,opt,name=depressed,proto3" json:"depressed,omitempty"`
	Pressed              uint32    `protobuf:"fixed32,11,opt,name=pressed,proto3" json:"pressed,omitempty"`
	Released             uint32    `protobuf:"fixed32,12,opt,name=released,proto3" json:"released,omitempty"`
	Analog               []float64 `protobuf:"fixed64,13,rep,packed,name=analog,proto3" json:"analog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_24c2a9f4cd96d406, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetShown() int32 {
	if m != nil {
		return m.Shown
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetHover() []int64 {
	if m != nil {
		return m.Hover
	}
	return nil
}

func (m *Response) GetUnhover() []int64 {
	if m != nil {
		return m.Unhover
	}
	return nil
}

func (m *Response) GetSelect() []int64 {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *Response) GetDeselect() []int64 {
	if m != nil {
		return m.Deselect
	}
	return nil
}

func (m *Response) GetViewloc() *Location {
	if m != nil {
		return m.Viewloc
	}
	return nil
}

func (m *Response) GetToolloc() *Location {
	if m != nil {
		return m.Toolloc
	}
	return nil
}

func (m *Response) GetOffsetloc() *Location {
	if m != nil {
		return m.Offsetloc
	}
	return nil
}

func (m *Response) GetDepressed() uint32 {
	if m != nil {
		return m.Depressed
	}
	return 0
}

func (m *Response) GetPressed() uint32 {
	if m != nil {
		return m.Pressed
	}
	return 0
}

func (m *Response) GetReleased() uint32 {
	if m != nil {
		return m.Released
	}
	return 0
}

func (m *Response) GetAnalog() []float64 {
	if m != nil {
		return m.Analog
	}
	return nil
}

func init() {
	proto.RegisterType((*Geometry)(nil), "Infovis.Geometry")
	proto.RegisterType((*Location)(nil), "Infovis.Location")
	proto.RegisterType((*Request)(nil), "Infovis.Request")
	proto.RegisterType((*Response)(nil), "Infovis.Response")
}

func init() { proto.RegisterFile("infovis.proto3", fileDescriptor_24c2a9f4cd96d406) }

var fileDescriptor_24c2a9f4cd96d406 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0xe5, 0xa6, 0xcd, 0x8f, 0x67, 0x40, 0x60, 0x10, 0xb2, 0x10, 0x8b, 0xa8, 0xab, 0x20,
	0xa4, 0x22, 0xc1, 0x1b, 0xb0, 0x41, 0x48, 0x2c, 0x90, 0xdf, 0x20, 0xd3, 0xde, 0x76, 0x22, 0xd2,
	0x38, 0xc4, 0xee, 0x4f, 0xf2, 0x1e, 0xb0, 0xe1, 0x0d, 0x78, 0x44, 0x56, 0xe8, 0x5e, 0xff, 0x74,
	0x58, 0x0c, 0x68, 0x76, 0xe7, 0x7c, 0xf7, 0x2a, 0x39, 0x3e, 0x56, 0xc2, 0x1f, 0x37, 0xdd, 0x56,
	0x1f, 0x1b, 0xb3, 0xea, 0x07, 0x6d, 0xf5, 0x7b, 0x91, 0x7d, 0x72, 0x7e, 0xf9, 0x9b, 0xf1, 0xfc,
	0x23, 0xe8, 0x3d, 0xd8, 0x61, 0x14, 0x82, 0xcf, 0xb7, 0x43, 0xbd, 0x97, 0xac, 0x64, 0xd5, 0x42,
	0x91, 0x46, 0xd6, 0x6c, 0xa0, 0x93, 0xb3, 0x92, 0x55, 0x89, 0x22, 0x8d, 0xcc, 0x8e, 0x3d, 0xc8,
	0xc4, 0xed, 0xa1, 0x46, 0xb6, 0xaf, 0xcd, 0x57, 0x39, 0x77, 0x0c, 0x35, 0xb2, 0x75, 0x67, 0x8d,
	0x5c, 0x94, 0x09, 0x32, 0xd4, 0xc8, 0x7a, 0x6d, 0xce, 0x32, 0x2d, 0x93, 0x8a, 0x29, 0xd2, 0x9e,
	0x8d, 0x32, 0x8b, 0x6c, 0xf4, 0x6c, 0x92, 0x79, 0x64, 0x13, 0x32, 0xd3, 0x4c, 0x20, 0x8b, 0x92,
	0x21, 0x43, 0x4d, 0xef, 0xd0, 0xed, 0x20, 0x79, 0xc9, 0xaa, 0x4c, 0x91, 0xa6, 0x7c, 0x70, 0xb6,
	0xf2, 0xaa, 0x64, 0x55, 0xa1, 0x48, 0x23, 0xdb, 0xb5, 0x63, 0x2f, 0xaf, 0x5d, 0x3e, 0xd4, 0xcb,
	0x1f, 0x8c, 0xe7, 0x9f, 0xf5, 0xba, 0xb6, 0x8d, 0xee, 0x62, 0x30, 0xe6, 0x1e, 0xfe, 0x57, 0xb0,
	0x59, 0x64, 0x97, 0x60, 0x49, 0x64, 0x14, 0x6c, 0xd0, 0xf6, 0x44, 0x87, 0x67, 0x8a, 0xb4, 0x67,
	0x67, 0xb9, 0x88, 0xec, 0xec, 0xd9, 0x28, 0xd3, 0xc8, 0x46, 0xcf, 0x26, 0x99, 0x45, 0x36, 0x2d,
	0x7f, 0xce, 0x78, 0xa6, 0xe0, 0xdb, 0x01, 0x0c, 0x05, 0x37, 0xb7, 0xfa, 0x14, 0x2e, 0x05, 0xb5,
	0x90, 0x3c, 0xdb, 0x83, 0x31, 0xf5, 0x0e, 0x28, 0x5a, 0xa1, 0x82, 0x15, 0xcf, 0xf9, 0x62, 0x00,
	0x03, 0x96, 0xe2, 0xe5, 0xca, 0x19, 0xf1, 0x9a, 0xa7, 0x87, 0xde, 0xc0, 0x60, 0xe5, 0xbc, 0x4c,
	0xaa, 0xab, 0x77, 0x4f, 0x57, 0xfe, 0xfe, 0x57, 0xe1, 0xee, 0x95, 0x5f, 0x10, 0x2f, 0x78, 0xba,
	0x81, 0x16, 0x2c, 0xd0, 0xad, 0x25, 0xca, 0x3b, 0xf1, 0x86, 0x67, 0xc7, 0x06, 0x4e, 0xad, 0x5e,
	0x53, 0xfa, 0xbb, 0xcf, 0x08, 0x15, 0xaa, 0xb0, 0x81, 0xcb, 0x56, 0xeb, 0x16, 0x97, 0xb3, 0x7b,
	0x97, 0xfd, 0x86, 0x78, 0xcb, 0x0b, 0xbd, 0xdd, 0x1a, 0xb0, 0xb8, 0x9e, 0xdf, 0xb7, 0x7e, 0xd9,
	0x59, 0x7e, 0x4f, 0x78, 0xae, 0xc0, 0xf4, 0xba, 0x33, 0x74, 0x60, 0xac, 0xa4, 0xf3, 0xfd, 0x38,
	0xf3, 0xef, 0x82, 0x6e, 0xf5, 0x11, 0x06, 0x99, 0xd0, 0xf1, 0x9c, 0xc1, 0xfd, 0x43, 0xe7, 0xf8,
	0x9c, 0x78, 0xb0, 0xd8, 0x87, 0x81, 0x16, 0xd6, 0x36, 0xf4, 0xe1, 0x9c, 0x78, 0xc9, 0xf3, 0x0d,
	0xf8, 0x49, 0x4a, 0x93, 0xe8, 0xef, 0x76, 0x95, 0x3d, 0xa4, 0xab, 0xfc, 0x61, 0x5d, 0x15, 0xff,
	0xef, 0x4a, 0xbc, 0xe2, 0xc5, 0x06, 0xfa, 0x01, 0x8c, 0x81, 0x8d, 0xff, 0x46, 0x2e, 0x00, 0x8f,
	0x1d, 0x66, 0x57, 0x34, 0x0b, 0x16, 0x8f, 0x37, 0x40, 0x0b, 0x35, 0x8e, 0xae, 0x69, 0x14, 0x3d,
	0x56, 0x52, 0x77, 0x75, 0xab, 0x77, 0xf2, 0x11, 0x7d, 0x9c, 0xde, 0x7d, 0x78, 0xf6, 0x6b, 0xf6,
	0x24, 0x64, 0xf9, 0x82, 0xff, 0x99, 0x9b, 0xc3, 0xf6, 0x26, 0x75, 0x7f, 0x9c, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x97, 0xc8, 0x3e, 0x96, 0x82, 0x04, 0x00, 0x00,
}
