/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Infovis.Response');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Infovis.Location');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Infovis.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Infovis.Response.repeatedFields_, null);
};
goog.inherits(proto.Infovis.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Infovis.Response.displayName = 'proto.Infovis.Response';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Infovis.Response.repeatedFields_ = [3,4,5,6,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Infovis.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.Infovis.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Infovis.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Infovis.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    shown: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hoverList: jspb.Message.getRepeatedField(msg, 3),
    unhoverList: jspb.Message.getRepeatedField(msg, 4),
    selectList: jspb.Message.getRepeatedField(msg, 5),
    deselectList: jspb.Message.getRepeatedField(msg, 6),
    viewloc: (f = msg.getViewloc()) && proto.Infovis.Location.toObject(includeInstance, f),
    toolloc: (f = msg.getToolloc()) && proto.Infovis.Location.toObject(includeInstance, f),
    depressed: jspb.Message.getFieldWithDefault(msg, 9, 0),
    pressed: jspb.Message.getFieldWithDefault(msg, 10, 0),
    released: jspb.Message.getFieldWithDefault(msg, 11, 0),
    analogList: jspb.Message.getRepeatedFloatingPointField(msg, 12)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Infovis.Response}
 */
proto.Infovis.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Infovis.Response;
  return proto.Infovis.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Infovis.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Infovis.Response}
 */
proto.Infovis.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShown(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setHoverList(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setUnhoverList(value);
      break;
    case 5:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setSelectList(value);
      break;
    case 6:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt64());
      msg.setDeselectList(value);
      break;
    case 7:
      var value = new proto.Infovis.Location;
      reader.readMessage(value,proto.Infovis.Location.deserializeBinaryFromReader);
      msg.setViewloc(value);
      break;
    case 8:
      var value = new proto.Infovis.Location;
      reader.readMessage(value,proto.Infovis.Location.deserializeBinaryFromReader);
      msg.setToolloc(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setDepressed(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setPressed(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setReleased(value);
      break;
    case 12:
      var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
      msg.setAnalogList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Infovis.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Infovis.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Infovis.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Infovis.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShown();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHoverList();
  if (f.length > 0) {
    writer.writePackedInt64(
      3,
      f
    );
  }
  f = message.getUnhoverList();
  if (f.length > 0) {
    writer.writePackedInt64(
      4,
      f
    );
  }
  f = message.getSelectList();
  if (f.length > 0) {
    writer.writePackedInt64(
      5,
      f
    );
  }
  f = message.getDeselectList();
  if (f.length > 0) {
    writer.writePackedInt64(
      6,
      f
    );
  }
  f = message.getViewloc();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.Infovis.Location.serializeBinaryToWriter
    );
  }
  f = message.getToolloc();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.Infovis.Location.serializeBinaryToWriter
    );
  }
  f = message.getDepressed();
  if (f !== 0) {
    writer.writeFixed32(
      9,
      f
    );
  }
  f = message.getPressed();
  if (f !== 0) {
    writer.writeFixed32(
      10,
      f
    );
  }
  f = message.getReleased();
  if (f !== 0) {
    writer.writeFixed32(
      11,
      f
    );
  }
  f = message.getAnalogList();
  if (f.length > 0) {
    writer.writePackedDouble(
      12,
      f
    );
  }
};


/**
 * optional int32 shown = 1;
 * @return {number}
 */
proto.Infovis.Response.prototype.getShown = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.Infovis.Response.prototype.setShown = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.Infovis.Response.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.Infovis.Response.prototype.setMessage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated int64 hover = 3;
 * @return {!Array<number>}
 */
proto.Infovis.Response.prototype.getHoverList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<number>} value */
proto.Infovis.Response.prototype.setHoverList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.Infovis.Response.prototype.addHover = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Infovis.Response.prototype.clearHoverList = function() {
  this.setHoverList([]);
};


/**
 * repeated int64 unhover = 4;
 * @return {!Array<number>}
 */
proto.Infovis.Response.prototype.getUnhoverList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<number>} value */
proto.Infovis.Response.prototype.setUnhoverList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.Infovis.Response.prototype.addUnhover = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Infovis.Response.prototype.clearUnhoverList = function() {
  this.setUnhoverList([]);
};


/**
 * repeated int64 select = 5;
 * @return {!Array<number>}
 */
proto.Infovis.Response.prototype.getSelectList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<number>} value */
proto.Infovis.Response.prototype.setSelectList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.Infovis.Response.prototype.addSelect = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Infovis.Response.prototype.clearSelectList = function() {
  this.setSelectList([]);
};


/**
 * repeated int64 deselect = 6;
 * @return {!Array<number>}
 */
proto.Infovis.Response.prototype.getDeselectList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/** @param {!Array<number>} value */
proto.Infovis.Response.prototype.setDeselectList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.Infovis.Response.prototype.addDeselect = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Infovis.Response.prototype.clearDeselectList = function() {
  this.setDeselectList([]);
};


/**
 * optional Location viewloc = 7;
 * @return {?proto.Infovis.Location}
 */
proto.Infovis.Response.prototype.getViewloc = function() {
  return /** @type{?proto.Infovis.Location} */ (
    jspb.Message.getWrapperField(this, proto.Infovis.Location, 7));
};


/** @param {?proto.Infovis.Location|undefined} value */
proto.Infovis.Response.prototype.setViewloc = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Infovis.Response.prototype.clearViewloc = function() {
  this.setViewloc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Infovis.Response.prototype.hasViewloc = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Location toolloc = 8;
 * @return {?proto.Infovis.Location}
 */
proto.Infovis.Response.prototype.getToolloc = function() {
  return /** @type{?proto.Infovis.Location} */ (
    jspb.Message.getWrapperField(this, proto.Infovis.Location, 8));
};


/** @param {?proto.Infovis.Location|undefined} value */
proto.Infovis.Response.prototype.setToolloc = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Infovis.Response.prototype.clearToolloc = function() {
  this.setToolloc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Infovis.Response.prototype.hasToolloc = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional fixed32 depressed = 9;
 * @return {number}
 */
proto.Infovis.Response.prototype.getDepressed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.Infovis.Response.prototype.setDepressed = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional fixed32 pressed = 10;
 * @return {number}
 */
proto.Infovis.Response.prototype.getPressed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.Infovis.Response.prototype.setPressed = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional fixed32 released = 11;
 * @return {number}
 */
proto.Infovis.Response.prototype.getReleased = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.Infovis.Response.prototype.setReleased = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * repeated double analog = 12;
 * @return {!Array<number>}
 */
proto.Infovis.Response.prototype.getAnalogList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 12));
};


/** @param {!Array<number>} value */
proto.Infovis.Response.prototype.setAnalogList = function(value) {
  jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 */
proto.Infovis.Response.prototype.addAnalog = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Infovis.Response.prototype.clearAnalogList = function() {
  this.setAnalogList([]);
};


